### ISSUE TITLE
Release v2.2.0 sees an increase in dust and sea salt emissions

### ISSUE THREAD

**Issue by vbuchard** [GEOS-ESM/GOCART#239]
- Just a notification that GOCART Release v2.2.0 sees an increase in dust and sea salt emissions (~ factor 2) compared to previous version that is currently under investigation.

**Comment by acollow** [comment]
This increase is in response to switching the MAPL_GetGrid call to local instead of global. To keep the call as local, an update needs to be made to Chem_UtilResVal in the process library that incorporates the number of processors and how the faces of the cube are split up (ie. Nx and Ny in AGCM.rc...or even better, ACGM_IM).

**Comment by mathomp4** [comment]
I'll mention @bena-nasa @atrayano @aoloso but I think I know a fix.

**Comment by vbuchard** [comment]
@mathomp4 That's correct. It has been fixed.

**Comment by mathomp4** [comment]
Okay. I'll close this
